Carrier.create!([
  {name: "Egyptair", iata_code: "MS", alliance: "Star Alliance", logo: "egyptair-logo-vector.png"},
  {name: "Air China", iata_code: "CA", alliance: "Star Alliance", logo: "air-china-logo-vector.png"},
  {name: "Air New Zealand", iata_code: "NZ", alliance: "Star Alliance", logo: "air-new-zealand-logo.png"},
  {name: "Asiana Airlines", iata_code: "OZ", alliance: "Star Alliance", logo: "asiana-airlines-logo-preview.png"},
  {name: "SWISS International Air Lines", iata_code: "LX", alliance: "Star Alliance", logo: "swissair-logo-vector-01.png"},
  {name: "All Nippon Airways", iata_code: "NH", alliance: "Star Alliance", logo: "ana-logo-all-all-nippon-airways-5.png"},
  {name: "Air Canada", iata_code: "AC", alliance: "Star Alliance", logo: "aircanada-vector.jpg"},
  {name: "Lufthansa", iata_code: "LH", alliance: "Star Alliance", logo: "lufthansa-logo-vector.png"},
  {name: "Scandinavian Airlines System (SAS)", iata_code: "SK", alliance: "Star Alliance", logo: "scandinavian-airlines-logo.png"},
  {name: "Singapore Airlines", iata_code: "SQ", alliance: "Star Alliance", logo: "singapore-airlines-logo.png"},
  {name: "Aegean Airlines", iata_code: "A3", alliance: "Star Alliance", logo: nil},
  {name: "Aer Arann", iata_code: "RE", alliance: " ", logo: nil},
  {name: "Aer Lingus", iata_code: "EI", alliance: " ", logo: nil},
  {name: "Aeroflot Russian Airlines", iata_code: "SU", alliance: "SkyTeam", logo: nil},
  {name: "Aerolineas Argentinas", iata_code: "AR", alliance: " ", logo: nil},
  {name: "Aeromexico", iata_code: "AM", alliance: "SkyTeam", logo: nil},
  {name: "Air Algerie", iata_code: "AH", alliance: " ", logo: nil},
  {name: "Air Astana", iata_code: "KC", alliance: " ", logo: nil},
  {name: "Air Europa", iata_code: "UX", alliance: "SkyTeam", logo: nil},
  {name: "Air France", iata_code: "AF", alliance: "SkyTeam", logo: nil},
  {name: "Air India", iata_code: "AI", alliance: "Star Alliance", logo: nil},
  {name: "Air Malta", iata_code: "KM", alliance: " ", logo: nil},
  {name: "Air Namibia", iata_code: "SW", alliance: " ", logo: nil},
  {name: "Air Seychelles", iata_code: "HM", alliance: " ", logo: nil},
  {name: "Air Tahiti", iata_code: "VT", alliance: " ", logo: nil},
  {name: "Air Zimbabwe", iata_code: "UM", alliance: " ", logo: nil},
  {name: "Alaska Airlines", iata_code: "AS", alliance: " ", logo: nil},
  {name: "Alitalia", iata_code: "AZ", alliance: "SkyTeam", logo: nil},
  {name: "American Airlines", iata_code: "AA", alliance: "Oneworld", logo: nil},
  {name: "Arik Air", iata_code: "W3", alliance: " ", logo: nil},
  {name: "Atlantic Airways", iata_code: "RC", alliance: " ", logo: nil},
  {name: "Aurigny", iata_code: "GR", alliance: " ", logo: nil},
  {name: "Austrian Airlines", iata_code: "OS", alliance: "Star Alliance", logo: nil},
  {name: "Avianca", iata_code: "AV", alliance: " ", logo: nil},
  {name: "Azerbaijan Hava Yollary", iata_code: "J2", alliance: " ", logo: nil},
  {name: "Bangkok Airways", iata_code: "PG", alliance: " ", logo: nil},
  {name: "Blue1", iata_code: "KF", alliance: "Star Alliance", logo: nil},
  {name: "British Airways", iata_code: "BA", alliance: "Oneworld", logo: nil},
  {name: "Brussels Airlines", iata_code: "SN", alliance: "Star Alliance", logo: nil},
  {name: "Bulgaria Air", iata_code: "FB", alliance: " ", logo: nil},
  {name: "Cathay Pacific", iata_code: "CX", alliance: "Oneworld", logo: nil},
  {name: "Czech Airlines", iata_code: "OK", alliance: "SkyTeam", logo: nil},
  {name: "China Airlines", iata_code: "CI", alliance: "SkyTeam", logo: nil},
  {name: "China Eastern Airlines", iata_code: "MU", alliance: "SkyTeam", logo: nil},
  {name: "China Southern Airlines", iata_code: "CZ", alliance: "SkyTeam", logo: nil},
  {name: "Croatia Airlines", iata_code: "OU", alliance: "Star Alliance", logo: nil},
  {name: "Cyprus Airways", iata_code: "CY", alliance: " ", logo: nil},
  {name: "Delta Air Lines", iata_code: "DL", alliance: "SkyTeam", logo: nil},
  {name: "Eastern Airways", iata_code: "T3", alliance: " ", logo: nil},
  {name: "El Al Israel Airlines", iata_code: "LY", alliance: " ", logo: nil},
  {name: "Emirates", iata_code: "EK", alliance: " ", logo: nil},
  {name: "Estonian Air", iata_code: "OV", alliance: " ", logo: nil},
  {name: "Ethiopian Airlines", iata_code: "ET", alliance: "Star Alliance", logo: nil},
  {name: "Etihad Airways", iata_code: "EY", alliance: " ", logo: nil},
  {name: "Eva Air", iata_code: "BR", alliance: "Star Alliance", logo: nil},
  {name: "Finnair", iata_code: "AY", alliance: "Oneworld", logo: nil},
  {name: "Flybe", iata_code: "BE", alliance: " ", logo: nil},
  {name: "Garuda Indonesia", iata_code: "GA", alliance: "SkyTeam", logo: nil},
  {name: "Gulf Air", iata_code: "GF", alliance: " ", logo: nil},
  {name: "HAHN Air", iata_code: "HR", alliance: " ", logo: nil},
  {name: "Hong Kong Airlines", iata_code: "HX", alliance: " ", logo: nil},
  {name: "Iberia", iata_code: "IB", alliance: "Oneworld", logo: nil},
  {name: "Icelandair", iata_code: "FI", alliance: " ", logo: nil},
  {name: "Japan Airlines", iata_code: "JL", alliance: "Oneworld", logo: nil},
  {name: "Jet Airways", iata_code: "9W", alliance: " ", logo: nil},
  {name: "Kenya Airways", iata_code: "KQ", alliance: "SkyTeam", logo: nil},
  {name: "KLM Royal Dutch Airlines", iata_code: "KL", alliance: "SkyTeam", logo: nil},
  {name: "Korean Air", iata_code: "KE", alliance: "SkyTeam", logo: nil},
  {name: "Kuwait Airways", iata_code: "KU", alliance: " ", logo: nil},
  {name: "LAN Colombia", iata_code: "LA", alliance: "Oneworld", logo: nil},
  {name: "LOT - Polish Airlines", iata_code: "LO", alliance: "Star Alliance", logo: nil},
  {name: "Luxair", iata_code: "LG", alliance: " ", logo: nil},
  {name: "Malaysia Airlines", iata_code: "MH", alliance: "Oneworld", logo: nil},
  {name: "Middle East Airlines", iata_code: "ME", alliance: "SkyTeam", logo: nil},
  {name: "Meridiana", iata_code: "IG", alliance: " ", logo: nil},
  {name: "Mexicana", iata_code: "MX", alliance: "Oneworld", logo: nil},
  {name: "Northwest Airlines", iata_code: "NW", alliance: " ", logo: nil},
  {name: "Norwegian Air Shuttle", iata_code: "DY", alliance: " ", logo: nil},
  {name: "Olympic Air", iata_code: "OA", alliance: " ", logo: nil},
  {name: "Oman Air", iata_code: "WY", alliance: " ", logo: nil},
  {name: "Rossiya-Russia Airlines", iata_code: "FV", alliance: " ", logo: nil},
  {name: "Qantas Airways", iata_code: "QF", alliance: "Oneworld", logo: nil},
  {name: "Qatar Airways", iata_code: "QR", alliance: "Oneworld", logo: nil},
  {name: "Royal Air Maroc", iata_code: "AT", alliance: " ", logo: nil},
  {name: "Royal Brunei Airlines", iata_code: "BI", alliance: " ", logo: nil},
  {name: "Royal Jordanian", iata_code: "RJ", alliance: "Oneworld", logo: nil},
  {name: "Siberia Airlines", iata_code: "S7", alliance: "Oneworld", logo: nil},
  {name: "Saudi Arabian Airlines", iata_code: "SV", alliance: " ", logo: nil},
  {name: "South African Airways", iata_code: "SA", alliance: "Star Alliance", logo: nil},
  {name: "Spanair", iata_code: "JK", alliance: "Star Alliance", logo: nil},
  {name: "SriLankan Airlines", iata_code: "UL", alliance: "Oneworld", logo: nil},
  {name: "TAM Airlines", iata_code: "JJ", alliance: "Oneworld", logo: nil},
  {name: "TAP Portugal", iata_code: "TP", alliance: "Star Alliance", logo: nil},
  {name: "Tarom", iata_code: "RO", alliance: "SkyTeam", logo: nil},
  {name: "Transaero Airlines", iata_code: "UN", alliance: " ", logo: nil},
  {name: "Tunisair", iata_code: "TU", alliance: " ", logo: nil},
  {name: "Ukraine International Airlines", iata_code: "PS", alliance: " ", logo: nil},
  {name: "Uzbekistan Airways", iata_code: "HY", alliance: " ", logo: nil},
  {name: "Vietnam Airlines", iata_code: "VN", alliance: "SkyTeam", logo: nil},
  {name: "Virgin Atlantic Airways", iata_code: "VS", alliance: " ", logo: nil},
  {name: "Xiamen Airlines", iata_code: "MF", alliance: "SkyTeam", logo: nil},
  {name: "Shanghai Airlines", iata_code: "FM", alliance: "CSH", logo: nil},
  {name: "Turkish Airlines", iata_code: "TK", alliance: "Star Alliance", logo: "turkish-airlines-thy--eps--vector-logo.png"},
  {name: "Thai Airways International", iata_code: "TG", alliance: "Star Alliance", logo: "thai-airways-vector-logo.png"},
  {name: "US Airways", iata_code: "US", alliance: "Oneworld", logo: "us-airways-logo.png"},
  {name: "United Airlines", iata_code: "UA", alliance: "Star Alliance", logo: "united-airlines-logo-vector.png"}
])
